/**
 * 统一错误映射
 * 
 * 此文件由 scripts/generateErrorSelectors.ts 自动生成
 * 请勿手动修改，如需添加中文翻译请修改 errorMessages.ts
 */

// 错误定义接口
export interface ErrorDef {
  name: string;
  message: string;
}

// 选择器 -> 错误定义（用于 0x 格式错误）
export const ErrorsBySelector: Record<string, ErrorDef> = {
  '0x001afc01': { name: 'DefaultGroupIdNotSet', message: '当前未设置默认NFT' },
  '0x003b2682': { name: 'AlreadyJoined', message: '已加入，不能重复加入' },
  '0x00821e6f': { name: 'ZeroFactory', message: '工厂合约地址不能为空' },
  '0x00d023bb': { name: 'RoundExceedsJoinRound', message: '轮次超过加入轮次' },
  '0x01f09857': { name: 'SourceAddressHasNoCode', message: '规则源地址未部署合约' },
  '0x029790c7': { name: 'ChatAlreadyActivated', message: '群聊已激活，不能重复激活' },
  '0x02a5acaa': { name: 'ScopeSourceFailed', message: '发言资格源读取失败' },
  '0x045670bc': { name: 'TrialAccountAlreadyAdded', message: '体验地址已存在，不能重复添加' },
  '0x05d3b44e': { name: 'InvalidExtension', message: '无效的扩展' },
  '0x06250401': { name: 'AmountTooLarge', message: '输入数量过大，请减少数量后重试' },
  '0x074d7a6b': { name: 'LastBlocksOfPhaseCannotJoin', message: `每轮最后${process.env.NEXT_PUBLIC_JOIN_END_PHASE_BLOCKS}个区块不能加入` },
  '0x075d47dd': { name: 'VerifyVotesZero', message: '验证票为零' },
  '0x077294b9': { name: 'MinStakeZero', message: '最小参与代币数必须大于0' },
  '0x079a14e3': { name: 'VerificationRuleEmpty', message: '验证规则不能为空' },
  '0x08f4b989': { name: 'AlreadyInOtherGroup', message: '已在其他链群中，不能重复加入' },
  '0x08fe2dec': { name: 'NotJoinedAction', message: '未加入该行动' },
  '0x0a47c558': { name: 'DuplicateAddress', message: '地址重复，不能重复加入' },
  '0x0b5bb4c3': { name: 'GroupNotActive', message: '链群未激活' },
  '0x0bc2eb6a': { name: 'ActionIdNotExist', message: '行动ID不存在' },
  '0x0bff3530': { name: 'ManagerAddressHasNoCode', message: 'Manager 地址未部署合约' },
  '0x0cab3901': { name: 'AccountAlreadyJoined', message: '账户已加入，不能重复加入' },
  '0x0d3d9acc': { name: 'HolderIndexOutOfBounds', message: '持有者索引超出范围' },
  '0x0dc149f0': { name: 'AlreadyInitialized', message: '已初始化，无需再次初始化' },
  '0x0f974c0a': { name: 'GroupNameEmpty', message: 'NFT名称不能为空' },
  '0x105722a2': { name: 'PostingNotAllowed', message: '该群聊已暂停发言' },
  '0x118fd7b8': { name: 'AlreadyVerified', message: '已验证，不能重复验证' },
  '0x152b2af8': { name: 'CannotJoinInactiveGroup', message: '无法加入未激活的链群' },
  '0x159ba83f': { name: 'ExtensionActionIdMismatch', message: '扩展行动ID不匹配' },
  '0x15ae6727': { name: 'InvalidSupply', message: '无效的供应量' },
  '0x172fa9d6': { name: 'MentionAllUnauthorized', message: '只有群 owner、delegate 或 GroupAdmin 管理员 NFT 可以发送 @所有人' },
  '0x17793beb': { name: 'ActionNotVoted', message: '该行动本轮没有投票' },
  '0x19ca070d': { name: 'ExtensionTokenAddressMismatch', message: '扩展代币地址不匹配' },
  '0x1ba68870': { name: 'JoinedAmountIsZero', message: '加入数量为0' },
  '0x1c3ba277': { name: 'BanSourceFailed', message: '禁言状态源读取失败' },
  '0x1dc37264': { name: 'ChatNotActivated', message: '群聊未激活' },
  '0x1eb00b06': { name: 'InvalidTokenAddress', message: '无效的代币地址' },
  '0x1f2a2005': { name: 'ZeroAmount', message: '转账数量不能为0' },
  '0x20068f59': { name: 'NotEligible2UpdateRandomSeed', message: '不符合更新随机种子的条件' },
  '0x2112c77f': { name: 'VoteWeightZero', message: '投票权重为 0' },
  '0x220839c9': { name: 'InvalidTokenSymbol', message: '无效的代币符号' },
  '0x220f9ee1': { name: 'InvalidMinMaxJoinAmount', message: '最小参与代币数不能为0' },
  '0x23e986aa': { name: 'ExceedsGroupMaxJoinAmount', message: '超过链群最大参与代币量，不能加入' },
  '0x241414c1': { name: 'TargetSenderIdZero', message: '目标 sender NFT ID 不能为 0' },
  '0x24663556': { name: 'NotVerifier', message: '不是验证者，无法执行此操作' },
  '0x28bd1cb1': { name: 'ActionNotVotedInCurrentRound', message: '该行动本轮未投票' },
  '0x28c49c8e': { name: 'InvalidQuotedMessageId', message: '引用消息不存在或无效' },
  '0x291e5a36': { name: 'GroupDelegateGroupMismatch', message: '代理 NFT 身份与当前群聊不匹配' },
  '0x2c16e660': { name: 'TokenNotLOVE20', message: '目标代币不是 LOVE20 代币' },
  '0x2c431f7d': { name: 'GroupDelegateHasNoCode', message: 'GroupDelegate 合约地址未部署' },
  '0x2fcd1a0f': { name: 'AmountBelowMinimum', message: '数量低于最小值' },
  '0x30512d9a': { name: 'GroupMemberAddressHasNoCode', message: 'GroupMember 地址未部署合约' },
  '0x34ad25cc': { name: 'LaunchNotEnded', message: '公平发射尚未结束' },
  '0x35047135': { name: 'NotChatOwner', message: '当前钱包不是群 owner' },
  '0x353caec0': { name: 'SenderNotGroupOwner', message: '只有NFT持有人可以设置默认NFT' },
  '0x368e710a': { name: 'InvalidGroupId', message: '无效的链群ID' },
  '0x37668688': { name: 'NativeTokenNotAccepted', message: '不能直接向 Zap 合约转入原生币' },
  '0x3aa08a1c': { name: 'MaxContentLengthZero', message: '最大内容长度不能为0' },
  '0x3b290c8a': { name: 'ZeroRatio', message: '二次分配比例不能为零，请修改' },
  '0x3e0673a5': { name: 'NoGovVotes', message: '没有治理票' },
  '0x3f1035e9': { name: 'TooManyMentionedSenderIds', message: '提及的 NFT 身份超过上限' },
  '0x401b6ade': { name: 'InvalidAccountAddress', message: '无效的账户地址' },
  '0x43ad20fc': { name: 'AmountIsZero', message: '数量不能为0' },
  '0x4508e970': { name: 'InvalidGroupActionTokenAddress', message: '无效的链群行动代币地址' },
  '0x4512ff19': { name: 'GroupDefaultsGroupMismatch', message: '默认 NFT 身份与当前群聊不匹配' },
  '0x4642d71a': { name: 'InsufficientActivationMinGovRatio', message: '治理票比例不足' },
  '0x46ce455e': { name: 'TargetMemberIdZero', message: '目标成员 NFT ID 不能为 0' },
  '0x4848f1d2': { name: 'ActionAlreadyRegisteredToOtherAction', message: '行动已注册到其他行动' },
  '0x48ac329c': { name: 'GroupNameTooLong', message: '链群名称过长' },
  '0x4a6464df': { name: 'ManagerGroupNameUnavailable', message: '管理器无法读取 NFT 名称' },
  '0x4dd82a81': { name: 'DuplicateAdminId', message: '管理员 NFT 不能重复' },
  '0x4ecfe35c': { name: 'InvalidMaxJoinAmountRatio', message: '无效的最大加入代币量比例' },
  '0x4f706af0': { name: 'VerificationKeyLengthExceeded', message: '验证信息的关键词长度超出限制' },
  '0x547c8ac8': { name: 'JoinAmountZero', message: '加入数量为零' },
  '0x5531b495': { name: 'TooManyRecipients', message: '接收者过多' },
  '0x55ce7178': { name: 'VerificationInfoLengthMismatch', message: '验证信息长度不匹配' },
  '0x55f6968b': { name: 'InvalidJoinTokenPair', message: '无效的加入代币对' },
  '0x5bc3a4b9': { name: 'BanThresholdTooHigh', message: '禁言投票阈值过高' },
  '0x5bd85db5': { name: 'OnlyGroupOwner', message: '只有链群服务者可以操作' },
  '0x5c6d7b73': { name: 'IdenticalTokens', message: '不能使用两个相同的代币' },
  '0x5c7bfbe9': { name: 'InvalidFactoryAddress', message: '无效的工厂地址' },
  '0x5ce6354c': { name: 'NotChatOwnerOrDelegateIdOwner', message: '当前钱包不是群 owner 或有效 delegate 持有人' },
  '0x5d0ff12d': { name: 'TitleEmpty', message: '标题不能为空' },
  '0x61ab9564': { name: 'GroupDefaultsHasNoCode', message: 'GroupDefaults 合约地址未部署' },
  '0x61fdbbd3': { name: 'GroupBanListAddressHasNoCode', message: 'GroupBanList 地址未部署合约' },
  '0x63db10b5': { name: 'CannotDeactivateInActivatedRound', message: '链群需要在激活的下一个轮次，才能关闭' },
  '0x63eea57d': { name: 'InvalidJoinTokenFactory', message: '无效的加入代币工厂' },
  '0x63eecb99': { name: 'InsufficientGovRatio', message: '治理票比例不足' },
  '0x646cf558': { name: 'AlreadyClaimed', message: '已领取，不能重复领取' },
  '0x648564d3': { name: 'InvalidRatio', message: '无效的比例' },
  '0x64d9b4d8': { name: 'ScoresMustIncrease', message: '验证得分必须增加' },
  '0x65bf3e8b': { name: 'ScoreExceedsMax', message: '得分超过了最大得分' },
  '0x65c7efcc': { name: 'NoContribution', message: '没有申购记录' },
  '0x670ff944': { name: 'InvalidParentToken', message: '无效的父代币' },
  '0x687a2e3f': { name: 'TrialAccountZero', message: '体验地址不能为空' },
  '0x694832c9': { name: 'RoundNotReadyToMint', message: '该轮次还不能铸造激励' },
  '0x6a003ec3': { name: 'GroupNotExist', message: 'NFT不存在' },
  '0x6a25ec6f': { name: 'LaunchAlreadyEnded', message: '公平发射已结束' },
  '0x6d363c45': { name: 'NoRewardAvailable', message: '没有激励可用' },
  '0x6dd5833e': { name: 'ActionIdNotFound', message: '行动ID没有找到' },
  '0x6e0f544a': { name: 'RoundHasNotStartedYet', message: '轮次尚未开始' },
  '0x6e34b2c9': { name: 'InvalidExtensionFactory', message: '无效的扩展工厂' },
  '0x6ef9fe7c': { name: 'OnlyAccountOrExtensionOrDelegate', message: '只有所属账户、扩展或委托人可以调用' },
  '0x7185cf6b': { name: 'InvalidMessageId', message: '无效的消息 ID' },
  '0x71ab6d98': { name: 'OnlyExtensionOrDelegate', message: '只有扩展或委托人可以操作' },
  '0x745dc627': { name: 'NoStakedLiquidity', message: '没有质押获取治理票，不能质押token获取加速激励' },
  '0x753ed00d': { name: 'TrialAccountNotInWaitingList', message: '体验地址不在等待列表中，不能加入' },
  '0x755b33c0': { name: 'ManagerPaymentFailed', message: '管理器支付失败' },
  '0x7721d498': { name: 'TrialAlreadyJoined', message: '体验地址已加入，不能重复加入' },
  '0x7818a60e': { name: 'NoActiveGroups', message: '您当前没有激活的链群，不能参加行动' },
  '0x7c78edb8': { name: 'TargetAddressZero', message: '目标地址不能为零地址' },
  '0x7cdcd530': { name: 'AdminBanSourceAddressHasNoCode', message: 'AdminBanSource 地址未部署合约' },
  '0x7d1f6366': { name: 'NotWhiteListAddress', message: '该地址不在白名单' },
  '0x826e77e8': { name: 'GroupJoinScopeSourceAddressHasNoCode', message: 'GroupJoinScopeSource 地址未部署合约' },
  '0x85a5c617': { name: 'ContentEmpty', message: '消息内容不能为空' },
  '0x87d2b2a7': { name: 'SenderAddressNotSenderIdOwner', message: '当前钱包不是默认 NFT 身份持有人' },
  '0x87f82fe2': { name: 'AdminIdsLimitExceeded', message: '管理员 NFT 数量超过上限' },
  '0x8aa3a72f': { name: 'InvalidToAddress', message: '无效的目标地址' },
  '0x8b203445': { name: 'MinSupportToOpposeRatioZero', message: '支持与反对比例下限不能为0' },
  '0x8e9c6e1c': { name: 'RoundNotStarted', message: '本轮尚未开始，请等待轮次开始后再试' },
  '0x8ed5f448': { name: 'MaxRandomAccountsZero', message: '最大随机账户数量必须大于0' },
  '0x8fe0a65f': { name: 'AmountIsGreaterThanReserve', message: '数量超过储备金' },
  '0x90f98e69': { name: 'NativeTransferFailed', message: '原生币转账失败，请检查对应收款地址是否可接收原生币' },
  '0x9148e78e': { name: 'NotRegisteredExtensionInFactory', message: '工厂中未注册的扩展' },
  '0x920d9292': { name: 'ZeroRouter', message: '路由合约地址不能为空' },
  '0x929189c1': { name: 'PluginAddressHasNoCode', message: '插件地址未部署合约' },
  '0x92acdb29': { name: 'ExtensionNotInitialized', message: '扩展未初始化' },
  '0x92c44259': { name: 'InvalidStartIndex', message: '无效的起始索引' },
  '0x9526fdba': { name: 'DefaultGroupIdAlreadySet', message: '该NFT已是当前默认NFT' },
  '0x961c9a4f': { name: 'InvalidToken', message: '无效的代币合约地址' },
  '0x965cd536': { name: 'NotEnoughWaitingBlocks', message: '等待区块数不足，请耐心等待' },
  '0x970d9702': { name: 'PromisedWaitingPhasesMustBeGreaterOrEqualThanBefore', message: '承诺等待的阶段数必须大于或等于之前的阶段数' },
  '0x97198fa6': { name: 'UnstakeAlreadyRequested', message: '已申请解除质押，还未过解锁期或未取走资产，不能再次质押' },
  '0x99b9530a': { name: 'ScoresExceedVotesNum', message: '验证得分超过投票数量' },
  '0x9a208e05': { name: 'GroupNameAlreadyExists', message: 'NFT名称已存在' },
  '0x9ad318ff': { name: 'ExceedsActionMaxJoinAmount', message: '超过行动最大参与代币量，不能加入' },
  '0x9af70448': { name: 'ZeroAmount', message: '转账数量不能为0' },
  '0x9b1ace7d': { name: 'UnexpectedManagerERC721Received', message: '管理器收到非预期 NFT' },
  '0x9b50a4dc': { name: 'UniswapLpMintedIsZero', message: 'Uniswap LP铸造数量为零' },
  '0x9cb4340e': { name: 'ERC20InsufficientAllowance', message: 'ERC20授权额度不足，请先授权' },
  '0x9de11e05': { name: 'UnauthorizedGroupBanListManager', message: '当前钱包无权管理 GroupBanList' },
  '0x9f588bb4': { name: 'ContentTooLong', message: '消息内容过长' },
  '0x9fb13b87': { name: 'OnlyOneSubmitPerRound', message: '每个轮次，1个地址只能提交1个行动' },
  '0x9fbfc589': { name: 'AlreadySubmitted', message: '该行动已提交，请勿重复提交' },
  '0xa06891e2': { name: 'DistrustVoteExceedsVerifyVotes', message: '不信任票超过验证票' },
  '0xa1c92f02': { name: 'GroupAlreadyActivated', message: '链群已激活，不能重复激活' },
  '0xa2065abe': { name: 'VerificationInfoLengthMismatch', message: '验证信息长度不匹配' },
  '0xa24a13a6': { name: 'ArrayLengthMismatch', message: '数组长度不匹配' },
  '0xa2b52a54': { name: 'InvalidRound', message: '无效的轮次' },
  '0xa31bafe3': { name: 'UnauthorizedGroupAdminManager', message: '当前钱包无权管理 GroupAdmin' },
  '0xa4f81929': { name: 'TokensAlreadyClaimed', message: '代币已经领取' },
  '0xa565e55c': { name: 'VoteNotFound', message: '未找到投票记录' },
  '0xa569b1a1': { name: 'PairMissingOrEmpty', message: '流动性池不存在或暂无流动性，请同时输入两种代币数量' },
  '0xa748da06': { name: 'StakeAmountMustBeSet', message: '质押数量必须大于0' },
  '0xa82c9674': { name: 'ZeroTokenA', message: '代币A地址不能为空' },
  '0xa8b98bb6': { name: 'BanVoteWeightSourceUnavailable', message: '禁言投票权重源不可用' },
  '0xa9b1c0d9': { name: 'InvalidActivationMinGovRatio', message: '激活治理票比例无效' },
  '0xa9cc8792': { name: 'BanRejected', message: '当前发言地址或 NFT 已被禁言' },
  '0xaaa7d29c': { name: 'TrialAmountZero', message: '体验代币数量不能为空' },
  '0xaaeae134': { name: 'GovVotedBanSourceAddressHasNoCode', message: 'GovVotedBanSource 地址未部署合约' },
  '0xaafa066e': { name: 'OriginScoresEmpty', message: '原始分数为空' },
  '0xaafa4b02': { name: 'GroupNameInvalidCharacters', message: '链群名称中含有无效字符' },
  '0xab1f07dd': { name: 'ScopeRejected', message: '当前默认 NFT 身份没有发言资格' },
  '0xab23ae90': { name: 'ScoresExceedAccountCount', message: '得分超过了地址数量' },
  '0xab82a248': { name: 'ZeroContribution', message: '申购数量为零' },
  '0xac083e30': { name: 'ERC20InsufficientBalance', message: 'ERC20余额不足' },
  '0xad1991f5': { name: 'ZeroToken', message: '代币地址不能为空' },
  '0xae1e3f91': { name: 'VoteUnchanged', message: '投票未变化' },
  '0xaeab1c0b': { name: 'ERC20InvalidReturn', message: 'ERC20转账返回值异常，请检查代币合约兼容性' },
  '0xaec0699e': { name: 'CannotSubmitAction', message: '您没有权限提交行动，请先质押获取足够代理票数' },
  '0xaf2411a3': { name: 'ManagerApprovalFailed', message: '管理器 NFT 授权失败' },
  '0xb0f2f9d1': { name: 'InvalidJoinTokenAddress', message: '无效的加入代币地址' },
  '0xb15ca316': { name: 'ClaimDelayNotPassed', message: '当前还不能领取，请下一区块再来领取' },
  '0xb1749e97': { name: 'RoundNotFinished', message: '轮次未结束' },
  '0xb2a93375': { name: 'ZeroTokenB', message: '代币B地址不能为空' },
  '0xb7fe70ae': { name: 'MultipleActionIdsFound', message: '找到多个行动ID' },
  '0xb951d9d6': { name: 'NoTokensToBurn', message: '没有代币可以销毁' },
  '0xbb55fd27': { name: 'InsufficientLiquidity', message: '流动性不足' },
  '0xbc760cfe': { name: 'NativeValueMismatch', message: '原生币转账金额与收款总额不一致' },
  '0xbe9cd064': { name: 'NotAllowedToStakeAtRoundZero', message: '不允许在第0轮进行质押' },
  '0xbeea6d6c': { name: 'ParentTokenNotSet', message: '父代币未设置' },
  '0xc2e5347d': { name: 'EmptyBatch', message: '批量列表不能为空' },
  '0xc30436e9': { name: 'ExceedsMaxSupply', message: '超过最大供应量' },
  '0xc394a433': { name: 'NotJoined', message: '不是行动参与者，无法执行此操作' },
  '0xc4309ac8': { name: 'GroupAccountsFull', message: '链群账户已满，不能再加入' },
  '0xc527094f': { name: 'CannotVote', message: '没有剩余治理票，无法投票' },
  '0xc5747798': { name: 'UnauthorizedGroupMemberManager', message: '当前钱包无权管理 GroupMember' },
  '0xc6107f87': { name: 'ERC20BalanceQueryFailed', message: 'ERC20余额查询失败' },
  '0xc94f8246': { name: 'VotesMustBeGreaterThanZero', message: '投票数量必须大于0' },
  '0xc9c77505': { name: 'AlreadyManaged', message: '该群聊已由当前管理器管理' },
  '0xc9d2c178': { name: 'NotEnoughReward', message: '激励不足，无法铸造' },
  '0xcb9e9842': { name: 'RecentRoundsZero', message: '最近轮次数不能为 0' },
  '0xcc1f40e6': { name: 'NotEnoughVotesLeft', message: '投票数量不足' },
  '0xce0a57ff': { name: 'NotEnoughRewardToBurn', message: '激励不足，无法销毁' },
  '0xd226f9d4': { name: 'InsufficientLiquidityMinted', message: 'LP铸造数量低于最小值，请调整数量或滑点后重试' },
  '0xd3a14033': { name: 'InvalidExtensionAddress', message: '无效的扩展地址' },
  '0xd5040ab4': { name: 'ERC20AllowanceQueryFailed', message: 'ERC20授权额度查询失败' },
  '0xd567cb6d': { name: 'TokenSymbolExists', message: '代币符号已存在' },
  '0xd6616002': { name: 'ScoresAndAccountsLengthMismatch', message: '分数和地址数量不匹配' },
  '0xd92e233d': { name: 'ZeroAddress', message: '地址不能为零地址' },
  '0xdab5b147': { name: 'TrialProviderMismatch', message: '体验地址与提供者不匹配，不能加入' },
  '0xdd17bfd6': { name: 'MaxAdminIdsZero', message: '管理员 NFT 上限不能为 0' },
  '0xdd1b7065': { name: 'SenderPairLengthMismatch', message: 'senderId 与 senderAddress 数量不一致' },
  '0xddefae28': { name: 'AlreadyMinted', message: '激励已铸造，不能重复铸造' },
  '0xdee26e4c': { name: 'InvalidReason', message: '无效的理由' },
  '0xe169fb70': { name: 'NotEligibleToLaunchToken', message: '不符合启动代币的条件' },
  '0xe181969e': { name: 'ERC20TransferFailed', message: 'ERC20转账失败，请检查对应收款地址和代币规则' },
  '0xe23d88e6': { name: 'WrappedNativeToken', message: '原生币路径不能直接选择包装原生币' },
  '0xe2918e9f': { name: 'RecipientCannotBeSelf', message: '接收者不能是自己' },
  '0xe5e356d3': { name: 'ZeroWrappedNativeToken', message: '包装原生币地址不能为空' },
  '0xe6319cd0': { name: 'DistrustVoteZeroAmount', message: '不信任票数量为零' },
  '0xe661ce90': { name: 'GroupMemberScopeAddressHasNoCode', message: 'GroupMemberScope 地址未部署合约' },
  '0xe666d54f': { name: 'PhaseBlocksZero', message: '阶段区块数不能为 0' },
  '0xe6c4247b': { name: 'InvalidAddress', message: '无效地址' },
  '0xe803932d': { name: 'GroupCapacityExceeded', message: '超过链群容量' },
  '0xe8ed8ec4': { name: 'InvalidActivationStakeAmount', message: '激活质押数量无效' },
  '0xe98204b2': { name: 'TotalLpExceedsBalance', message: '总LP数量超过余额' },
  '0xeb758b9c': { name: 'GroupAdminHasNoCode', message: 'GroupAdmin 合约地址未部署' },
  '0xebd13c1e': { name: 'PromisedWaitingPhasesOutOfRange', message: '承诺等待的阶段数超出许可范围' },
  '0xed24d0e7': { name: 'ManagerMintCostChanged', message: 'NFT 铸造费用已变化，请刷新后重试' },
  '0xed3ba6a6': { name: 'Reentrant', message: '交易执行中，请勿重复操作' },
  '0xeef9087e': { name: 'UnstakeNotRequested', message: '未申请解除质押' },
  '0xef28bd44': { name: 'ZeroRecipient', message: '收款地址不能为零地址' },
  '0xf09762b6': { name: 'LaunchAlreadyExists', message: '公平发射已存在' },
  '0xf33b2011': { name: 'JoinAmountLessThanMinStake', message: '加入数量小于最小参与代币数' },
  '0xf4b3b1bc': { name: 'NativeTransferFailed', message: '原生币转账失败，请检查对应收款地址是否可接收原生币' },
  '0xf4d678b8': { name: 'InsufficientBalance', message: '余额不足' },
  '0xf55a5f82': { name: 'NotEnoughWaitingBlocks', message: '等待区块数不足，请耐心等待' },
  '0xf62bae8c': { name: 'ActionNotSubmitted', message: '该行动本轮未被推举，无法投票' },
  '0xf6c6b5be': { name: 'GroupAdminAddressHasNoCode', message: 'GroupAdmin 地址未部署合约' },
  '0xf790fcc7': { name: 'ModifierAddressCannotBeZero', message: '修改者地址不能为零地址' },
  '0xf8d2906c': { name: 'NotMinter', message: '不是铸造者，无法执行此操作' },
  '0xfa5dbe08': { name: 'ArrayLengthMismatch', message: '数组长度不匹配' },
  '0xfbd8cb1c': { name: 'ZeroTo', message: '接收地址不能为空' },
  '0xfc764866': { name: 'DuplicateMentionedSenderId', message: '提及的 NFT 身份不能重复' },
  '0xfdf915a7': { name: 'TrialAccountIsProvider', message: '体验地址不能是自己的地址' },
  '0xfe40467d': { name: 'ExtensionCreatorMismatch', message: '扩展创建者不匹配' },
  '0xfeddba5d': { name: 'TrialArrayLengthMismatch', message: '体验地址列表长度不匹配' },
};

// 错误名称 -> 错误定义（用于 ErrorName() 格式错误）
export const ErrorsByName: Record<string, ErrorDef> = {
  'AccountAlreadyJoined': { name: 'AccountAlreadyJoined', message: '账户已加入，不能重复加入' },
  'ActionAlreadyRegisteredToOtherAction': { name: 'ActionAlreadyRegisteredToOtherAction', message: '行动已注册到其他行动' },
  'ActionIdNotExist': { name: 'ActionIdNotExist', message: '行动ID不存在' },
  'ActionIdNotFound': { name: 'ActionIdNotFound', message: '行动ID没有找到' },
  'ActionNotSubmitted': { name: 'ActionNotSubmitted', message: '该行动本轮未被推举，无法投票' },
  'ActionNotVoted': { name: 'ActionNotVoted', message: '该行动本轮没有投票' },
  'ActionNotVotedInCurrentRound': { name: 'ActionNotVotedInCurrentRound', message: '该行动本轮未投票' },
  'AdminBanSourceAddressHasNoCode': { name: 'AdminBanSourceAddressHasNoCode', message: 'AdminBanSource 地址未部署合约' },
  'AdminIdsLimitExceeded': { name: 'AdminIdsLimitExceeded', message: '管理员 NFT 数量超过上限' },
  'AlreadyClaimed': { name: 'AlreadyClaimed', message: '已领取，不能重复领取' },
  'AlreadyInitialized': { name: 'AlreadyInitialized', message: '已初始化，无需再次初始化' },
  'AlreadyInOtherGroup': { name: 'AlreadyInOtherGroup', message: '已在其他链群中，不能重复加入' },
  'AlreadyJoined': { name: 'AlreadyJoined', message: '已加入，不能重复加入' },
  'AlreadyManaged': { name: 'AlreadyManaged', message: '该群聊已由当前管理器管理' },
  'AlreadyMinted': { name: 'AlreadyMinted', message: '激励已铸造，不能重复铸造' },
  'AlreadySubmitted': { name: 'AlreadySubmitted', message: '该行动已提交，请勿重复提交' },
  'AlreadyVerified': { name: 'AlreadyVerified', message: '已验证，不能重复验证' },
  'AmountBelowMinimum': { name: 'AmountBelowMinimum', message: '数量低于最小值' },
  'AmountIsGreaterThanReserve': { name: 'AmountIsGreaterThanReserve', message: '数量超过储备金' },
  'AmountIsZero': { name: 'AmountIsZero', message: '数量不能为0' },
  'AmountTooLarge': { name: 'AmountTooLarge', message: '输入数量过大，请减少数量后重试' },
  'ArrayLengthMismatch': { name: 'ArrayLengthMismatch', message: '数组长度不匹配' },
  'BanRejected': { name: 'BanRejected', message: '当前发言地址或 NFT 已被禁言' },
  'BanSourceFailed': { name: 'BanSourceFailed', message: '禁言状态源读取失败' },
  'BanThresholdTooHigh': { name: 'BanThresholdTooHigh', message: '禁言投票阈值过高' },
  'BanVoteWeightSourceUnavailable': { name: 'BanVoteWeightSourceUnavailable', message: '禁言投票权重源不可用' },
  'CannotDeactivateInActivatedRound': { name: 'CannotDeactivateInActivatedRound', message: '链群需要在激活的下一个轮次，才能关闭' },
  'CannotJoinInactiveGroup': { name: 'CannotJoinInactiveGroup', message: '无法加入未激活的链群' },
  'CannotSubmitAction': { name: 'CannotSubmitAction', message: '您没有权限提交行动，请先质押获取足够代理票数' },
  'CannotVote': { name: 'CannotVote', message: '没有剩余治理票，无法投票' },
  'ChatAlreadyActivated': { name: 'ChatAlreadyActivated', message: '群聊已激活，不能重复激活' },
  'ChatNotActivated': { name: 'ChatNotActivated', message: '群聊未激活' },
  'ClaimDelayNotPassed': { name: 'ClaimDelayNotPassed', message: '当前还不能领取，请下一区块再来领取' },
  'ContentEmpty': { name: 'ContentEmpty', message: '消息内容不能为空' },
  'ContentTooLong': { name: 'ContentTooLong', message: '消息内容过长' },
  'DefaultGroupIdAlreadySet': { name: 'DefaultGroupIdAlreadySet', message: '该NFT已是当前默认NFT' },
  'DefaultGroupIdNotSet': { name: 'DefaultGroupIdNotSet', message: '当前未设置默认NFT' },
  'DistrustVoteExceedsVerifyVotes': { name: 'DistrustVoteExceedsVerifyVotes', message: '不信任票超过验证票' },
  'DistrustVoteZeroAmount': { name: 'DistrustVoteZeroAmount', message: '不信任票数量为零' },
  'DuplicateAddress': { name: 'DuplicateAddress', message: '地址重复，不能重复加入' },
  'DuplicateAdminId': { name: 'DuplicateAdminId', message: '管理员 NFT 不能重复' },
  'DuplicateMentionedSenderId': { name: 'DuplicateMentionedSenderId', message: '提及的 NFT 身份不能重复' },
  'EmptyBatch': { name: 'EmptyBatch', message: '批量列表不能为空' },
  'ERC20AllowanceQueryFailed': { name: 'ERC20AllowanceQueryFailed', message: 'ERC20授权额度查询失败' },
  'ERC20BalanceQueryFailed': { name: 'ERC20BalanceQueryFailed', message: 'ERC20余额查询失败' },
  'ERC20InsufficientAllowance': { name: 'ERC20InsufficientAllowance', message: 'ERC20授权额度不足，请先授权' },
  'ERC20InsufficientBalance': { name: 'ERC20InsufficientBalance', message: 'ERC20余额不足' },
  'ERC20InvalidReturn': { name: 'ERC20InvalidReturn', message: 'ERC20转账返回值异常，请检查代币合约兼容性' },
  'ERC20TransferFailed': { name: 'ERC20TransferFailed', message: 'ERC20转账失败，请检查对应收款地址和代币规则' },
  'ExceedsActionMaxJoinAmount': { name: 'ExceedsActionMaxJoinAmount', message: '超过行动最大参与代币量，不能加入' },
  'ExceedsGroupMaxJoinAmount': { name: 'ExceedsGroupMaxJoinAmount', message: '超过链群最大参与代币量，不能加入' },
  'ExceedsMaxSupply': { name: 'ExceedsMaxSupply', message: '超过最大供应量' },
  'ExtensionActionIdMismatch': { name: 'ExtensionActionIdMismatch', message: '扩展行动ID不匹配' },
  'ExtensionCreatorMismatch': { name: 'ExtensionCreatorMismatch', message: '扩展创建者不匹配' },
  'ExtensionNotInitialized': { name: 'ExtensionNotInitialized', message: '扩展未初始化' },
  'ExtensionTokenAddressMismatch': { name: 'ExtensionTokenAddressMismatch', message: '扩展代币地址不匹配' },
  'GovVotedBanSourceAddressHasNoCode': { name: 'GovVotedBanSourceAddressHasNoCode', message: 'GovVotedBanSource 地址未部署合约' },
  'GroupAccountsFull': { name: 'GroupAccountsFull', message: '链群账户已满，不能再加入' },
  'GroupAdminAddressHasNoCode': { name: 'GroupAdminAddressHasNoCode', message: 'GroupAdmin 地址未部署合约' },
  'GroupAdminHasNoCode': { name: 'GroupAdminHasNoCode', message: 'GroupAdmin 合约地址未部署' },
  'GroupAlreadyActivated': { name: 'GroupAlreadyActivated', message: '链群已激活，不能重复激活' },
  'GroupBanListAddressHasNoCode': { name: 'GroupBanListAddressHasNoCode', message: 'GroupBanList 地址未部署合约' },
  'GroupCapacityExceeded': { name: 'GroupCapacityExceeded', message: '超过链群容量' },
  'GroupDefaultsGroupMismatch': { name: 'GroupDefaultsGroupMismatch', message: '默认 NFT 身份与当前群聊不匹配' },
  'GroupDefaultsHasNoCode': { name: 'GroupDefaultsHasNoCode', message: 'GroupDefaults 合约地址未部署' },
  'GroupDelegateGroupMismatch': { name: 'GroupDelegateGroupMismatch', message: '代理 NFT 身份与当前群聊不匹配' },
  'GroupDelegateHasNoCode': { name: 'GroupDelegateHasNoCode', message: 'GroupDelegate 合约地址未部署' },
  'GroupJoinScopeSourceAddressHasNoCode': { name: 'GroupJoinScopeSourceAddressHasNoCode', message: 'GroupJoinScopeSource 地址未部署合约' },
  'GroupMemberAddressHasNoCode': { name: 'GroupMemberAddressHasNoCode', message: 'GroupMember 地址未部署合约' },
  'GroupMemberScopeAddressHasNoCode': { name: 'GroupMemberScopeAddressHasNoCode', message: 'GroupMemberScope 地址未部署合约' },
  'GroupNameAlreadyExists': { name: 'GroupNameAlreadyExists', message: 'NFT名称已存在' },
  'GroupNameEmpty': { name: 'GroupNameEmpty', message: 'NFT名称不能为空' },
  'GroupNameInvalidCharacters': { name: 'GroupNameInvalidCharacters', message: '链群名称中含有无效字符' },
  'GroupNameTooLong': { name: 'GroupNameTooLong', message: '链群名称过长' },
  'GroupNotActive': { name: 'GroupNotActive', message: '链群未激活' },
  'GroupNotExist': { name: 'GroupNotExist', message: 'NFT不存在' },
  'HolderIndexOutOfBounds': { name: 'HolderIndexOutOfBounds', message: '持有者索引超出范围' },
  'IdenticalTokens': { name: 'IdenticalTokens', message: '不能使用两个相同的代币' },
  'InsufficientActivationMinGovRatio': { name: 'InsufficientActivationMinGovRatio', message: '治理票比例不足' },
  'InsufficientBalance': { name: 'InsufficientBalance', message: '余额不足' },
  'InsufficientGovRatio': { name: 'InsufficientGovRatio', message: '治理票比例不足' },
  'InsufficientLiquidity': { name: 'InsufficientLiquidity', message: '流动性不足' },
  'InsufficientLiquidityMinted': { name: 'InsufficientLiquidityMinted', message: 'LP铸造数量低于最小值，请调整数量或滑点后重试' },
  'InvalidAccountAddress': { name: 'InvalidAccountAddress', message: '无效的账户地址' },
  'InvalidActivationMinGovRatio': { name: 'InvalidActivationMinGovRatio', message: '激活治理票比例无效' },
  'InvalidActivationStakeAmount': { name: 'InvalidActivationStakeAmount', message: '激活质押数量无效' },
  'InvalidAddress': { name: 'InvalidAddress', message: '无效地址' },
  'InvalidExtension': { name: 'InvalidExtension', message: '无效的扩展' },
  'InvalidExtensionAddress': { name: 'InvalidExtensionAddress', message: '无效的扩展地址' },
  'InvalidExtensionFactory': { name: 'InvalidExtensionFactory', message: '无效的扩展工厂' },
  'InvalidFactoryAddress': { name: 'InvalidFactoryAddress', message: '无效的工厂地址' },
  'InvalidGroupActionTokenAddress': { name: 'InvalidGroupActionTokenAddress', message: '无效的链群行动代币地址' },
  'InvalidGroupId': { name: 'InvalidGroupId', message: '无效的链群ID' },
  'InvalidJoinTokenAddress': { name: 'InvalidJoinTokenAddress', message: '无效的加入代币地址' },
  'InvalidJoinTokenFactory': { name: 'InvalidJoinTokenFactory', message: '无效的加入代币工厂' },
  'InvalidJoinTokenPair': { name: 'InvalidJoinTokenPair', message: '无效的加入代币对' },
  'InvalidMaxJoinAmountRatio': { name: 'InvalidMaxJoinAmountRatio', message: '无效的最大加入代币量比例' },
  'InvalidMessageId': { name: 'InvalidMessageId', message: '无效的消息 ID' },
  'InvalidMinMaxJoinAmount': { name: 'InvalidMinMaxJoinAmount', message: '最小参与代币数不能为0' },
  'InvalidParentToken': { name: 'InvalidParentToken', message: '无效的父代币' },
  'InvalidQuotedMessageId': { name: 'InvalidQuotedMessageId', message: '引用消息不存在或无效' },
  'InvalidRatio': { name: 'InvalidRatio', message: '无效的比例' },
  'InvalidReason': { name: 'InvalidReason', message: '无效的理由' },
  'InvalidRound': { name: 'InvalidRound', message: '无效的轮次' },
  'InvalidStartIndex': { name: 'InvalidStartIndex', message: '无效的起始索引' },
  'InvalidSupply': { name: 'InvalidSupply', message: '无效的供应量' },
  'InvalidToAddress': { name: 'InvalidToAddress', message: '无效的目标地址' },
  'InvalidToken': { name: 'InvalidToken', message: '无效的代币合约地址' },
  'InvalidTokenAddress': { name: 'InvalidTokenAddress', message: '无效的代币地址' },
  'InvalidTokenSymbol': { name: 'InvalidTokenSymbol', message: '无效的代币符号' },
  'JoinAmountLessThanMinStake': { name: 'JoinAmountLessThanMinStake', message: '加入数量小于最小参与代币数' },
  'JoinAmountZero': { name: 'JoinAmountZero', message: '加入数量为零' },
  'JoinedAmountIsZero': { name: 'JoinedAmountIsZero', message: '加入数量为0' },
  'LastBlocksOfPhaseCannotJoin': { name: 'LastBlocksOfPhaseCannotJoin', message: `每轮最后${process.env.NEXT_PUBLIC_JOIN_END_PHASE_BLOCKS}个区块不能加入` },
  'LaunchAlreadyEnded': { name: 'LaunchAlreadyEnded', message: '公平发射已结束' },
  'LaunchAlreadyExists': { name: 'LaunchAlreadyExists', message: '公平发射已存在' },
  'LaunchNotEnded': { name: 'LaunchNotEnded', message: '公平发射尚未结束' },
  'ManagerAddressHasNoCode': { name: 'ManagerAddressHasNoCode', message: 'Manager 地址未部署合约' },
  'ManagerApprovalFailed': { name: 'ManagerApprovalFailed', message: '管理器 NFT 授权失败' },
  'ManagerGroupNameUnavailable': { name: 'ManagerGroupNameUnavailable', message: '管理器无法读取 NFT 名称' },
  'ManagerMintCostChanged': { name: 'ManagerMintCostChanged', message: 'NFT 铸造费用已变化，请刷新后重试' },
  'ManagerPaymentFailed': { name: 'ManagerPaymentFailed', message: '管理器支付失败' },
  'MaxAdminIdsZero': { name: 'MaxAdminIdsZero', message: '管理员 NFT 上限不能为 0' },
  'MaxContentLengthZero': { name: 'MaxContentLengthZero', message: '最大内容长度不能为0' },
  'MaxRandomAccountsZero': { name: 'MaxRandomAccountsZero', message: '最大随机账户数量必须大于0' },
  'MentionAllUnauthorized': { name: 'MentionAllUnauthorized', message: '只有群 owner、delegate 或 GroupAdmin 管理员 NFT 可以发送 @所有人' },
  'MinStakeZero': { name: 'MinStakeZero', message: '最小参与代币数必须大于0' },
  'MinSupportToOpposeRatioZero': { name: 'MinSupportToOpposeRatioZero', message: '支持与反对比例下限不能为0' },
  'ModifierAddressCannotBeZero': { name: 'ModifierAddressCannotBeZero', message: '修改者地址不能为零地址' },
  'MultipleActionIdsFound': { name: 'MultipleActionIdsFound', message: '找到多个行动ID' },
  'NativeTokenNotAccepted': { name: 'NativeTokenNotAccepted', message: '不能直接向 Zap 合约转入原生币' },
  'NativeTransferFailed': { name: 'NativeTransferFailed', message: '原生币转账失败，请检查对应收款地址是否可接收原生币' },
  'NativeValueMismatch': { name: 'NativeValueMismatch', message: '原生币转账金额与收款总额不一致' },
  'NoActiveGroups': { name: 'NoActiveGroups', message: '您当前没有激活的链群，不能参加行动' },
  'NoContribution': { name: 'NoContribution', message: '没有申购记录' },
  'NoGovVotes': { name: 'NoGovVotes', message: '没有治理票' },
  'NoRewardAvailable': { name: 'NoRewardAvailable', message: '没有激励可用' },
  'NoStakedLiquidity': { name: 'NoStakedLiquidity', message: '没有质押获取治理票，不能质押token获取加速激励' },
  'NotAllowedToStakeAtRoundZero': { name: 'NotAllowedToStakeAtRoundZero', message: '不允许在第0轮进行质押' },
  'NotChatOwner': { name: 'NotChatOwner', message: '当前钱包不是群 owner' },
  'NotChatOwnerOrDelegateIdOwner': { name: 'NotChatOwnerOrDelegateIdOwner', message: '当前钱包不是群 owner 或有效 delegate 持有人' },
  'NotEligible2UpdateRandomSeed': { name: 'NotEligible2UpdateRandomSeed', message: '不符合更新随机种子的条件' },
  'NotEligibleToLaunchToken': { name: 'NotEligibleToLaunchToken', message: '不符合启动代币的条件' },
  'NotEnoughReward': { name: 'NotEnoughReward', message: '激励不足，无法铸造' },
  'NotEnoughRewardToBurn': { name: 'NotEnoughRewardToBurn', message: '激励不足，无法销毁' },
  'NotEnoughVotesLeft': { name: 'NotEnoughVotesLeft', message: '投票数量不足' },
  'NotEnoughWaitingBlocks': { name: 'NotEnoughWaitingBlocks', message: '等待区块数不足，请耐心等待' },
  'NotJoined': { name: 'NotJoined', message: '不是行动参与者，无法执行此操作' },
  'NotJoinedAction': { name: 'NotJoinedAction', message: '未加入该行动' },
  'NotMinter': { name: 'NotMinter', message: '不是铸造者，无法执行此操作' },
  'NoTokensToBurn': { name: 'NoTokensToBurn', message: '没有代币可以销毁' },
  'NotRegisteredExtensionInFactory': { name: 'NotRegisteredExtensionInFactory', message: '工厂中未注册的扩展' },
  'NotVerifier': { name: 'NotVerifier', message: '不是验证者，无法执行此操作' },
  'NotWhiteListAddress': { name: 'NotWhiteListAddress', message: '该地址不在白名单' },
  'OnlyAccountOrExtensionOrDelegate': { name: 'OnlyAccountOrExtensionOrDelegate', message: '只有所属账户、扩展或委托人可以调用' },
  'OnlyExtensionOrDelegate': { name: 'OnlyExtensionOrDelegate', message: '只有扩展或委托人可以操作' },
  'OnlyGroupOwner': { name: 'OnlyGroupOwner', message: '只有链群服务者可以操作' },
  'OnlyOneSubmitPerRound': { name: 'OnlyOneSubmitPerRound', message: '每个轮次，1个地址只能提交1个行动' },
  'OriginScoresEmpty': { name: 'OriginScoresEmpty', message: '原始分数为空' },
  'PairMissingOrEmpty': { name: 'PairMissingOrEmpty', message: '流动性池不存在或暂无流动性，请同时输入两种代币数量' },
  'ParentTokenNotSet': { name: 'ParentTokenNotSet', message: '父代币未设置' },
  'PhaseBlocksZero': { name: 'PhaseBlocksZero', message: '阶段区块数不能为 0' },
  'PluginAddressHasNoCode': { name: 'PluginAddressHasNoCode', message: '插件地址未部署合约' },
  'PostingNotAllowed': { name: 'PostingNotAllowed', message: '该群聊已暂停发言' },
  'PromisedWaitingPhasesMustBeGreaterOrEqualThanBefore': { name: 'PromisedWaitingPhasesMustBeGreaterOrEqualThanBefore', message: '承诺等待的阶段数必须大于或等于之前的阶段数' },
  'PromisedWaitingPhasesOutOfRange': { name: 'PromisedWaitingPhasesOutOfRange', message: '承诺等待的阶段数超出许可范围' },
  'RecentRoundsZero': { name: 'RecentRoundsZero', message: '最近轮次数不能为 0' },
  'RecipientCannotBeSelf': { name: 'RecipientCannotBeSelf', message: '接收者不能是自己' },
  'Reentrant': { name: 'Reentrant', message: '交易执行中，请勿重复操作' },
  'RoundExceedsJoinRound': { name: 'RoundExceedsJoinRound', message: '轮次超过加入轮次' },
  'RoundHasNotStartedYet': { name: 'RoundHasNotStartedYet', message: '轮次尚未开始' },
  'RoundNotFinished': { name: 'RoundNotFinished', message: '轮次未结束' },
  'RoundNotReadyToMint': { name: 'RoundNotReadyToMint', message: '该轮次还不能铸造激励' },
  'RoundNotStarted': { name: 'RoundNotStarted', message: '本轮尚未开始，请等待轮次开始后再试' },
  'ScopeRejected': { name: 'ScopeRejected', message: '当前默认 NFT 身份没有发言资格' },
  'ScopeSourceFailed': { name: 'ScopeSourceFailed', message: '发言资格源读取失败' },
  'ScoreExceedsMax': { name: 'ScoreExceedsMax', message: '得分超过了最大得分' },
  'ScoresAndAccountsLengthMismatch': { name: 'ScoresAndAccountsLengthMismatch', message: '分数和地址数量不匹配' },
  'ScoresExceedAccountCount': { name: 'ScoresExceedAccountCount', message: '得分超过了地址数量' },
  'ScoresExceedVotesNum': { name: 'ScoresExceedVotesNum', message: '验证得分超过投票数量' },
  'ScoresMustIncrease': { name: 'ScoresMustIncrease', message: '验证得分必须增加' },
  'SenderAddressNotSenderIdOwner': { name: 'SenderAddressNotSenderIdOwner', message: '当前钱包不是默认 NFT 身份持有人' },
  'SenderNotGroupOwner': { name: 'SenderNotGroupOwner', message: '只有NFT持有人可以设置默认NFT' },
  'SenderPairLengthMismatch': { name: 'SenderPairLengthMismatch', message: 'senderId 与 senderAddress 数量不一致' },
  'SourceAddressHasNoCode': { name: 'SourceAddressHasNoCode', message: '规则源地址未部署合约' },
  'StakeAmountMustBeSet': { name: 'StakeAmountMustBeSet', message: '质押数量必须大于0' },
  'TargetAddressZero': { name: 'TargetAddressZero', message: '目标地址不能为零地址' },
  'TargetMemberIdZero': { name: 'TargetMemberIdZero', message: '目标成员 NFT ID 不能为 0' },
  'TargetSenderIdZero': { name: 'TargetSenderIdZero', message: '目标 sender NFT ID 不能为 0' },
  'TitleEmpty': { name: 'TitleEmpty', message: '标题不能为空' },
  'TokenNotLOVE20': { name: 'TokenNotLOVE20', message: '目标代币不是 LOVE20 代币' },
  'TokensAlreadyClaimed': { name: 'TokensAlreadyClaimed', message: '代币已经领取' },
  'TokenSymbolExists': { name: 'TokenSymbolExists', message: '代币符号已存在' },
  'TooManyMentionedSenderIds': { name: 'TooManyMentionedSenderIds', message: '提及的 NFT 身份超过上限' },
  'TooManyRecipients': { name: 'TooManyRecipients', message: '接收者过多' },
  'TotalLpExceedsBalance': { name: 'TotalLpExceedsBalance', message: '总LP数量超过余额' },
  'TrialAccountAlreadyAdded': { name: 'TrialAccountAlreadyAdded', message: '体验地址已存在，不能重复添加' },
  'TrialAccountIsProvider': { name: 'TrialAccountIsProvider', message: '体验地址不能是自己的地址' },
  'TrialAccountNotInWaitingList': { name: 'TrialAccountNotInWaitingList', message: '体验地址不在等待列表中，不能加入' },
  'TrialAccountZero': { name: 'TrialAccountZero', message: '体验地址不能为空' },
  'TrialAlreadyJoined': { name: 'TrialAlreadyJoined', message: '体验地址已加入，不能重复加入' },
  'TrialAmountZero': { name: 'TrialAmountZero', message: '体验代币数量不能为空' },
  'TrialArrayLengthMismatch': { name: 'TrialArrayLengthMismatch', message: '体验地址列表长度不匹配' },
  'TrialProviderMismatch': { name: 'TrialProviderMismatch', message: '体验地址与提供者不匹配，不能加入' },
  'UnauthorizedGroupAdminManager': { name: 'UnauthorizedGroupAdminManager', message: '当前钱包无权管理 GroupAdmin' },
  'UnauthorizedGroupBanListManager': { name: 'UnauthorizedGroupBanListManager', message: '当前钱包无权管理 GroupBanList' },
  'UnauthorizedGroupMemberManager': { name: 'UnauthorizedGroupMemberManager', message: '当前钱包无权管理 GroupMember' },
  'UnexpectedManagerERC721Received': { name: 'UnexpectedManagerERC721Received', message: '管理器收到非预期 NFT' },
  'UniswapLpMintedIsZero': { name: 'UniswapLpMintedIsZero', message: 'Uniswap LP铸造数量为零' },
  'UnstakeAlreadyRequested': { name: 'UnstakeAlreadyRequested', message: '已申请解除质押，还未过解锁期或未取走资产，不能再次质押' },
  'UnstakeNotRequested': { name: 'UnstakeNotRequested', message: '未申请解除质押' },
  'VerificationInfoLengthMismatch': { name: 'VerificationInfoLengthMismatch', message: '验证信息长度不匹配' },
  'VerificationKeyLengthExceeded': { name: 'VerificationKeyLengthExceeded', message: '验证信息的关键词长度超出限制' },
  'VerificationRuleEmpty': { name: 'VerificationRuleEmpty', message: '验证规则不能为空' },
  'VerifyVotesZero': { name: 'VerifyVotesZero', message: '验证票为零' },
  'VoteNotFound': { name: 'VoteNotFound', message: '未找到投票记录' },
  'VotesMustBeGreaterThanZero': { name: 'VotesMustBeGreaterThanZero', message: '投票数量必须大于0' },
  'VoteUnchanged': { name: 'VoteUnchanged', message: '投票未变化' },
  'VoteWeightZero': { name: 'VoteWeightZero', message: '投票权重为 0' },
  'WrappedNativeToken': { name: 'WrappedNativeToken', message: '原生币路径不能直接选择包装原生币' },
  'ZeroAddress': { name: 'ZeroAddress', message: '地址不能为零地址' },
  'ZeroAmount': { name: 'ZeroAmount', message: '转账数量不能为0' },
  'ZeroContribution': { name: 'ZeroContribution', message: '申购数量为零' },
  'ZeroFactory': { name: 'ZeroFactory', message: '工厂合约地址不能为空' },
  'ZeroRatio': { name: 'ZeroRatio', message: '二次分配比例不能为零，请修改' },
  'ZeroRecipient': { name: 'ZeroRecipient', message: '收款地址不能为零地址' },
  'ZeroRouter': { name: 'ZeroRouter', message: '路由合约地址不能为空' },
  'ZeroTo': { name: 'ZeroTo', message: '接收地址不能为空' },
  'ZeroToken': { name: 'ZeroToken', message: '代币地址不能为空' },
  'ZeroTokenA': { name: 'ZeroTokenA', message: '代币A地址不能为空' },
  'ZeroTokenB': { name: 'ZeroTokenB', message: '代币B地址不能为空' },
  'ZeroWrappedNativeToken': { name: 'ZeroWrappedNativeToken', message: '包装原生币地址不能为空' },
};
