name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 根据项目需求选择 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: yarn install

      # 构建项目
      - name: Build
        env:
          BASE_PATH: /interface
          ASSET_PREFIX: /interface
          NEXT_PUBLIC_APP_VERSION: 1.0.6

          NEXT_PUBLIC_CHAIN: thinkium801
          NEXT_PUBLIC_THINKIUM_RPC_URL: https://rpc-testnet.ruleos.com
          NEXT_PUBLIC_NATIVE_TOKEN_SYMBOL: TKM
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_SYMBOL: TestTKM20
          NEXT_PUBLIC_TOKEN_DECIMALS: 18
          NEXT_PUBLIC_BLOCK_TIME: 255

          NEXT_PUBLIC_SEPOLIA_RPC_URL:
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: 3e08c0ee570fce9c29473eb34b0532c3
          NEXT_PUBLIC_FOUNDRY_CORE_ABI_PATH: ../LOVE20-core/out/
          NEXT_PUBLIC_FOUNDRY_PERIPHERAL_ABI_PATH: ../LOVE20-peripheral/out/
          NEXT_PUBLIC_BASE_PATH: /interface

          NEXT_PUBLIC_FIRST_TOKEN_SYMBOL: TestLOVE20
          NEXT_PUBLIC_WITHDRAW_WAITING_BLOCKS: 40
          NEXT_PUBLIC_CHILD_TOKEN_WAITING_BLOCKS: 236488
          NEXT_PUBLIC_PHASE_BLOCKS: 33784
          NEXT_PUBLIC_JOIN_END_PHASE_BLOCKS: 200
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MIN: 1
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MAX: 2
          NEXT_PUBLIC_SUBMIT_MIN_PER_THOUSAND: 5 # 0.5% gov votes
          NEXT_PUBLIC_ROUND_REWARD_GOV_PER_THOUSAND: 5 # 0.5%
          NEXT_PUBLIC_ROUND_REWARD_ACTION_PER_THOUSAND: 5 # 0.5%

          NEXT_PUBLIC_CONTRACT_ADDRESS_FEE_TO_SETTER:
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_FACTORY: '0xC13594c59F7B27774Deae27B68e9d3876c3C2A08'
          NEXT_PUBLIC_CONTRACT_ADDRESS_ROOT_PARENT_TOKEN: '0x015b1A506F2aa2B1ecC000aB799ED6C59005fBb3'
          NEXT_PUBLIC_CONTRACT_ADDRESS_TOKEN_FACTORY: '0x1748a29831D5E3dacB03E02dF6062A6Cdf0F96af'
          NEXT_PUBLIC_CONTRACT_ADDRESS_LAUNCH: '0x19C8E1E12D71E811ab5b70987579cbF2f856B388'
          NEXT_PUBLIC_CONTRACT_ADDRESS_STAKE: '0x11bBb48bAA8765b0394A13F6Aa406B13e940836A'
          NEXT_PUBLIC_CONTRACT_ADDRESS_SUBMIT: '0x50894a15d1b0A6D6223924a2ecE38f6e72d6ADFE'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VOTE: '0xba3498b9C1B95F64574A076EA05167c7d3435e3a'
          NEXT_PUBLIC_CONTRACT_ADDRESS_JOIN: '0xDe5256A1cf6022ef6af832181CCE617Aee585Dc9'
          NEXT_PUBLIC_CONTRACT_ADDRESS_RANDOM: '0x6a96c75ddd3ef68502E9C5c8B326438584341e32'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VERIFY: '0xD4506737c861697EB3B3616ee0E31c835a4432B2'
          NEXT_PUBLIC_CONTRACT_ADDRESS_MINT: '0x5B5D54443a979d9D7863803B9Dfac1b9A8f67565'

          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_TOKEN: '0x034D08a8102cE7CdEa5Dcc7b3109de24f261b3e6'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_SL_TOKEN: '0xE5Eb48cEf9E08B52001a62Cce20C46Cff25fEf9A'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_ST_TOKEN: '0x48Ef80983627dbAA167AE01a887F1078fCbCD7bD'

          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_DATAVIEWER: '0x8349d98589DFc81dC16d9a5b86b95df1Cc9beECc'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_ROUTER: '0x2A2Dc26469F9C8ccA09BbB5C1124bCaA758c014d'
          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_HUB: '0x9CE12E214F7d770E4d708f9BD140C5F8468b1E02'

          # 添加其他环境变量，如果有的话
        run: |
          yarn build
          cp out/index.html out/404.html

      # 检查静态文件
      - name: List build files
        run: ls -R out/

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # 如果需要自定义域名，可以添加以下内容
          # cname: your-custom-domain.com
