name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 根据项目需求选择 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: yarn install

      # 构建项目
      - name: Build
        env:
          BASE_PATH: /interface
          ASSET_PREFIX: /interface
          NEXT_PUBLIC_APP_VERSION: 1.1.0

          NEXT_PUBLIC_CHAIN: thinkium70001
          NEXT_PUBLIC_THINKIUM_RPC_URL: https://proxy1.thinkiumrpc.net
          NEXT_PUBLIC_NATIVE_TOKEN_SYMBOL: TKM
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_SYMBOL: TestTKM20
          NEXT_PUBLIC_TOKEN_DECIMALS: 18
          NEXT_PUBLIC_BLOCK_TIME: 255
          NEXT_PUBLIC_TOKEN_PREFIX: Test

          NEXT_PUBLIC_SEPOLIA_RPC_URL:
          NEXT_PUBLIC_FOUNDRY_CORE_ABI_PATH: ../LOVE20-core/out/
          NEXT_PUBLIC_FOUNDRY_PERIPHERAL_ABI_PATH: ../LOVE20-peripheral/out/
          NEXT_PUBLIC_BASE_PATH: /interface

          NEXT_PUBLIC_FIRST_TOKEN_SYMBOL: TestLOVE20
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_FUNDRAISING_GOAL: 100000000000000000 # 1e17 (0.1 TKM)
          NEXT_PUBLIC_PARENT_TOKEN_FUNDRAISING_GOAL: 20000000000000000000000000 # 2 * 1e7 * 1e18 (20 million tokens)
          NEXT_PUBLIC_WITHDRAW_WAITING_BLOCKS: 48 # 2 minutes
          NEXT_PUBLIC_MIN_GOV_REWARD_MINTS_TO_LAUNCH: 2 # how many gov reward mints  to launch one token
          NEXT_PUBLIC_PHASE_BLOCKS: 120 # 5 minutes
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MIN: 1
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MAX: 4
          NEXT_PUBLIC_SUBMIT_MIN_PER_THOUSAND: 3 # 0.3% gov votes
          NEXT_PUBLIC_JOIN_END_PHASE_BLOCKS: 8 # last 20 seconds fobid to join
          NEXT_PUBLIC_ACTION_REWARD_MIN_VOTE_PER_THOUSAND: 30 # 3%
          NEXT_PUBLIC_ROUND_REWARD_GOV_PER_THOUSAND: 1 # 0.1%
          NEXT_PUBLIC_ROUND_REWARD_ACTION_PER_THOUSAND: 1 # 0.1%

          NEXT_PUBLIC_CONTRACT_ADDRESS_ROOT_PARENT_TOKEN: '0xDe2929C78Ebb5aa9eFA2032C9DD732f9F3C73F71'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_FACTORY: '0x67337850a91b84EdEE86ab4571E713E2493C4c32'
          NEXT_PUBLIC_CONTRACT_ADDRESS_TOKEN_FACTORY: '0xDdD37c4623b156a6762e2194A66633C09BDa9552'
          NEXT_PUBLIC_CONTRACT_ADDRESS_LAUNCH: '0x84A823E10226679Ed7BcDD046d08F97a52EC2cf1'
          NEXT_PUBLIC_CONTRACT_ADDRESS_STAKE: '0x928cc255e6ACa047d7094c75C00a59A6E4bB11ba'
          NEXT_PUBLIC_CONTRACT_ADDRESS_SUBMIT: '0x6208C7C83a806b98c718128023f8276a0F34b73C'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VOTE: '0x4f65Ee40f13a88D6Ac6b8029d95fc5ceeea3a1c6'
          NEXT_PUBLIC_CONTRACT_ADDRESS_JOIN: '0x5b31D8A0676Ae756BF9CF5591bB2a9E8aB65F925'
          NEXT_PUBLIC_CONTRACT_ADDRESS_RANDOM: '0xD4af790DF0B1D95B3e09249ee50AC37CAcC73a89'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VERIFY: '0x0822F4C4783D73e1206DD24f48f27C972aCa0DAC'
          NEXT_PUBLIC_CONTRACT_ADDRESS_MINT: '0xF48cF3c6d687Cd8D218FD53A85Fb789f4831D1A0'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_TOKEN: '0xc1CfEee5fD4f726AC4E5AB804b33FA667d6cFD14'
          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_TOKENVIEWER: '0x4a395A1998aD04eBa71ca1ad68A0b4e5D15dAAe0'
          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_ROUNDVIEWER: '0x8B4F87E64809b9f162e5908DC1064025DA3C0268'
          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_HUB: '0xA6B78658F5327CfaE9FA8d68988520E75b44a396'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_ROUTER: '0x939B0E7A1FA207bBacC94622dD6A326739B7dBAE'

          # 添加其他环境变量，如果有的话
        run: |
          yarn build
          cp out/index.html out/404.html

      # 检查静态文件
      - name: List build files
        run: ls -R out/

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # 如果需要自定义域名，可以添加以下内容
          # cname: your-custom-domain.com
