name: Reusable Deploy to GitHub Pages (subdir)

on:
  workflow_call:
    inputs:
      install_script:
        type: string
        required: false
        default: 'yarn install'
      build_script:
        type: string
        required: false
        default: 'yarn build'
      node_version:
        type: string
        required: false
        default: '20'
      out_dir:
        type: string
        required: false
        default: 'out'
      destination_dir:
        type: string
        required: true
      publish_branch:
        type: string
        required: false
        default: 'gh-pages'
      base_path:
        type: string
        required: true
      asset_prefix:
        type: string
        required: false
        default: ''

      concurrency_group:
        type: string
        required: false
        default: 'gh-pages'
      cancel_in_progress:
        type: boolean
        required: false
        default: false

permissions:
  contents: write

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: ${{ inputs.cancel_in_progress }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: ${{ inputs.install_script }}

      # 设置 BASE_PATH/ASSET_PREFIX
      - name: Set BASE_PATH & ASSET_PREFIX
        run: |
          echo "BASE_PATH=${{ inputs.base_path }}" >> "$GITHUB_ENV"
          if [ -z "${{ inputs.asset_prefix }}" ]; then
            echo "ASSET_PREFIX=${{ inputs.base_path }}" >> "$GITHUB_ENV"
          else
            echo "ASSET_PREFIX=${{ inputs.asset_prefix }}" >> "$GITHUB_ENV"
          fi

      - name: Build
        run: ${{ inputs.build_script }}

      - name: Add 404.html (SPA routing)
        run: |
          if [ -f "${{ inputs.out_dir }}/index.html" ]; then
            cp "${{ inputs.out_dir }}/index.html" "${{ inputs.out_dir }}/404.html"
          fi

      - name: List build files
        run: ls -R "${{ inputs.out_dir }}/"

      - name: Deploy to GitHub Pages subdir
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.out_dir }}
          publish_branch: ${{ inputs.publish_branch }}
          destination_dir: ${{ inputs.destination_dir }}
          keep_files: true
