name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 根据项目需求选择 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: yarn install

      # 构建项目
      - name: Build
        env:
          BASE_PATH: /interface
          ASSET_PREFIX: /interface
          NEXT_PUBLIC_APP_VERSION: 1.0.6

          NEXT_PUBLIC_CHAIN: thinkium70001
          NEXT_PUBLIC_THINKIUM_RPC_URL: https://proxy1.thinkiumrpc.net
          NEXT_PUBLIC_NATIVE_TOKEN_SYMBOL: TKM
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_SYMBOL: TestTKM20
          NEXT_PUBLIC_TOKEN_DECIMALS: 18
          NEXT_PUBLIC_BLOCK_TIME: 255
          NEXT_PUBLIC_TOKEN_PREFIX: Test

          NEXT_PUBLIC_SEPOLIA_RPC_URL:
          NEXT_PUBLIC_FOUNDRY_CORE_ABI_PATH: ../LOVE20-core/out/
          NEXT_PUBLIC_FOUNDRY_PERIPHERAL_ABI_PATH: ../LOVE20-peripheral/out/
          NEXT_PUBLIC_BASE_PATH: /interface

          NEXT_PUBLIC_FIRST_TOKEN_SYMBOL: TestLOVE20
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_FUNDRAISING_GOAL: 100000000000000000 # 1e17 (0.1 TKM)
          NEXT_PUBLIC_PARENT_TOKEN_FUNDRAISING_GOAL: 20000000000000000000000000 # 2 * 1e7 * 1e18 (20 million tokens)
          NEXT_PUBLIC_WITHDRAW_WAITING_BLOCKS: 48 # 2 minutes
          NEXT_PUBLIC_MIN_GOV_REWARD_MINTS_TO_LAUNCH: 2 # how many gov reward mints  to launch one token
          NEXT_PUBLIC_PHASE_BLOCKS: 120 # 5 minutes
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MIN: 1
          NEXT_PUBLIC_PROMISED_WAITING_PHASES_MAX: 4
          NEXT_PUBLIC_SUBMIT_MIN_PER_THOUSAND: 3 # 0.3% gov votes
          NEXT_PUBLIC_JOIN_END_PHASE_BLOCKS: 8 # last 20 seconds fobid to join
          NEXT_PUBLIC_ACTION_REWARD_MIN_VOTE_PER_THOUSAND: 30 # 3%
          NEXT_PUBLIC_ROUND_REWARD_GOV_PER_THOUSAND: 1 # 0.1%
          NEXT_PUBLIC_ROUND_REWARD_ACTION_PER_THOUSAND: 1 # 0.1%

          NEXT_PUBLIC_CONTRACT_ADDRESS_ROOT_PARENT_TOKEN: '0xDe2929C78Ebb5aa9eFA2032C9DD732f9F3C73F71'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_FACTORY: '0x67337850a91b84EdEE86ab4571E713E2493C4c32'
          NEXT_PUBLIC_CONTRACT_ADDRESS_TOKEN_FACTORY: '0x479f75f696f0c30cFE6a1388AC982cC5b2D85241'
          NEXT_PUBLIC_CONTRACT_ADDRESS_LAUNCH: '0xC8257e61128edDCC7B5af60461945336b2cce4bA'
          NEXT_PUBLIC_CONTRACT_ADDRESS_STAKE: '0xe5aF1b0f6cE14296039d9505d8A91c77be36A0FD'
          NEXT_PUBLIC_CONTRACT_ADDRESS_SUBMIT: '0x5a9042b5544B8f997e3F95D73928a3cAb2144203'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VOTE: '0x45A7369719800B2cb43e75f69A9C3d02f02df5Ad'
          NEXT_PUBLIC_CONTRACT_ADDRESS_JOIN: '0xcEe483E0fd5543AEBA20AD55bB54bEB6A07569F9'
          NEXT_PUBLIC_CONTRACT_ADDRESS_RANDOM: '0x5939Aa9fBd1bCfc2F457b3fE96abB645c0042612'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VERIFY: '0x61461a09DcCdb55683770e23713Bc0Ba6784c64a'
          NEXT_PUBLIC_CONTRACT_ADDRESS_MINT: '0x4AaCb57E409acaB41EeEfd29967eb309C221413A'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_TOKEN: '0x83a4A156987d1A1EFe9ABB2fd882Fafd7CF887D2'

          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_DATAVIEWER: '0x709139dBe8F172d1d27557d84532A8cE7a76DCCa'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_ROUTER: '0x0770860fDEAC4af77412aC8bd7574eeEB0079E77'
          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_HUB: '0xe37E58E2192d115E0ECe861726d4849064C1E1b4'

          # 添加其他环境变量，如果有的话
        run: |
          yarn build
          cp out/index.html out/404.html

      # 检查静态文件
      - name: List build files
        run: ls -R out/

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # 如果需要自定义域名，可以添加以下内容
          # cname: your-custom-domain.com
